# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseComment',
            new_name='CourseComments',
        ),
    ]
