# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleTag', verbose_name='\u6587\u7ae0\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=50, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogType', verbose_name='\u535a\u5ba2\u7c7b\u578b'),
        ),
    ]
