# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=500, verbose_name='\u5f53\u65e5\u4e8b\u4ef6')),
            ],
            options={
                'verbose_name': '\u5173\u4e8e\u6211',
                'verbose_name_plural': '\u5173\u4e8e\u6211',
            },
        ),
    ]
