# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 22:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='description',
            field=models.TextField(verbose_name='\u5f53\u65e5\u4e8b\u4ef6'),
        ),
    ]
